n_points: 8
coordinates: [
    [1,2],
    [3,1],
    [5,4],
    [6,1],
    [2,5],
    [4,2],
    [7,2],
    [8,4],
]
base_coordinates: [0,0]
demands: [10, 15, 20, 25, 10, 15, 5, 10]
start_battery: 100.0
max_battery: 100.0
max_carry_weight: 100.0
max_velocity: 10.0
max_mission_time: 10000.0
drone_weight: 1.0
battery_consumption:
  alpha: 0.1
  beta: 0.1
  gamma: 0.1